/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Coleccion;
import Modelo.Computador;
import Modelo.Impresora;
import javax.swing.JOptionPane;

/**
 *
 * @author pipeg
 */
public class From_Ingresar extends javax.swing.JFrame {

    /**
     * Creates new form From_Ingresar
     */
    public From_Ingresar() {
        initComponents();
        this.jtxt_id.requestFocus();
        this.jlbl_marcapc.setVisible(false);
        this.jlbl_ram.setVisible(false);
        this.jtxt_marcaPc.setVisible(false);
        this.jtxt_ram.setVisible(false);
        this.jlbl_marcaimp.setVisible(false);
        this.jlbl_tipo.setVisible(false);
        this.jtxt_marcaImp.setVisible(false);
        this.jtxt_tipo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupProducto = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jbrtn_volver = new javax.swing.JButton();
        jbtn_ingresar = new javax.swing.JButton();
        jlbl_producot = new javax.swing.JPanel();
        jlbl_id = new javax.swing.JLabel();
        jlbl_nombre = new javax.swing.JLabel();
        jlbl_precio = new javax.swing.JLabel();
        jtxt_id = new javax.swing.JTextField();
        jtxt_nombre = new javax.swing.JTextField();
        jtxt_precio = new javax.swing.JTextField();
        jrbtn_computador = new javax.swing.JRadioButton();
        jrbtn_impresora = new javax.swing.JRadioButton();
        jlbl_marcapc = new javax.swing.JLabel();
        jlbl_ram = new javax.swing.JLabel();
        jtxt_marcaPc = new javax.swing.JTextField();
        jtxt_ram = new javax.swing.JTextField();
        jlbl_marcaimp = new javax.swing.JLabel();
        jlbl_tipo = new javax.swing.JLabel();
        jtxt_marcaImp = new javax.swing.JTextField();
        jtxt_tipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jbrtn_volver.setText("Volver");
        jbrtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrtn_volverActionPerformed(evt);
            }
        });

        jbtn_ingresar.setText("Ingresar");
        jbtn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_ingresar)
                    .addComponent(jbrtn_volver))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_ingresar)
                .addGap(18, 18, 18)
                .addComponent(jbrtn_volver)
                .addGap(65, 65, 65))
        );

        jlbl_producot.setBackground(new java.awt.Color(255, 255, 255));

        jlbl_id.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_id.setText("ID:");

        jlbl_nombre.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_nombre.setText("Nombre:");

        jlbl_precio.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_precio.setText("Precio:");

        jtxt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_precioActionPerformed(evt);
            }
        });

        buttonGroupProducto.add(jrbtn_computador);
        jrbtn_computador.setForeground(new java.awt.Color(0, 0, 0));
        jrbtn_computador.setText("Computador");
        jrbtn_computador.setToolTipText("");
        jrbtn_computador.setFocusable(false);
        jrbtn_computador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jrbtn_computadorFocusLost(evt);
            }
        });
        jrbtn_computador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn_computadorActionPerformed(evt);
            }
        });

        buttonGroupProducto.add(jrbtn_impresora);
        jrbtn_impresora.setForeground(new java.awt.Color(0, 0, 0));
        jrbtn_impresora.setText("Impresora");
        jrbtn_impresora.setFocusable(false);
        jrbtn_impresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn_impresoraActionPerformed(evt);
            }
        });

        jlbl_marcapc.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_marcapc.setText("Marca PC:");

        jlbl_ram.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_ram.setText("RAM:");

        jlbl_marcaimp.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_marcaimp.setText("Marca:");

        jlbl_tipo.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_tipo.setText("Tipo:");

        javax.swing.GroupLayout jlbl_producotLayout = new javax.swing.GroupLayout(jlbl_producot);
        jlbl_producot.setLayout(jlbl_producotLayout);
        jlbl_producotLayout.setHorizontalGroup(
            jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlbl_producotLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jlbl_producotLayout.createSequentialGroup()
                            .addComponent(jlbl_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_nombre)))
                    .addGroup(jlbl_producotLayout.createSequentialGroup()
                        .addComponent(jlbl_marcaimp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_marcapc))
                    .addGroup(jlbl_producotLayout.createSequentialGroup()
                        .addComponent(jlbl_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_ram, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlbl_producotLayout.createSequentialGroup()
                        .addGroup(jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxt_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jtxt_id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_nombre, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbtn_computador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbtn_impresora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jlbl_producotLayout.createSequentialGroup()
                        .addComponent(jtxt_marcaImp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_marcaPc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlbl_producotLayout.createSequentialGroup()
                        .addComponent(jtxt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_ram, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jlbl_producotLayout.setVerticalGroup(
            jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlbl_producotLayout.createSequentialGroup()
                .addGroup(jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlbl_producotLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_id)
                            .addComponent(jtxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_nombre)
                            .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_precio)
                            .addComponent(jtxt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jlbl_producotLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jrbtn_computador)
                        .addGap(18, 18, 18)
                        .addComponent(jrbtn_impresora)))
                .addGap(31, 31, 31)
                .addGroup(jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_marcapc)
                    .addComponent(jtxt_marcaPc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_marcaimp)
                    .addComponent(jtxt_marcaImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlbl_producotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_ram)
                    .addComponent(jtxt_ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_tipo)
                    .addComponent(jtxt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_producot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbl_producot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbrtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrtn_volverActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jbrtn_volverActionPerformed

    private void jtxt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_precioActionPerformed

    private void jrbtn_computadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn_computadorActionPerformed
        // TODO add your handling code here:
        
        if (jrbtn_computador.isSelected()){
            this.jlbl_marcapc.setVisible(true);
            this.jlbl_ram.setVisible(true);
            this.jtxt_marcaPc.setVisible(true);
            this.jtxt_ram.setVisible(true);
            this.jlbl_marcaimp.setVisible(false);
            this.jlbl_tipo.setVisible(false);
            this.jtxt_marcaImp.setVisible(false);
            this.jtxt_tipo.setVisible(false);
        }else{
            this.jrbtn_computador.setSelected(false);
            this.jlbl_marcapc.setVisible(false);
            this.jlbl_ram.setVisible(false);
            this.jtxt_marcaPc.setVisible(false);
            this.jtxt_ram.setVisible(false);
        }
    }//GEN-LAST:event_jrbtn_computadorActionPerformed

    private void jrbtn_impresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn_impresoraActionPerformed
        // TODO add your handling code here:
        
         if (jrbtn_impresora.isSelected()){
            this.jlbl_marcaimp.setVisible(true);
            this.jlbl_tipo.setVisible(true);
            this.jtxt_marcaImp.setVisible(true);
            this.jtxt_tipo.setVisible(true);
            this.jrbtn_computador.setSelected(false);
            this.jlbl_marcapc.setVisible(false);
            this.jlbl_ram.setVisible(false);
            this.jtxt_marcaPc.setVisible(false);
            this.jtxt_ram.setVisible(false);
        }else{
            
            this.jlbl_marcaimp.setVisible(false);
            this.jlbl_tipo.setVisible(false);
            this.jtxt_marcaImp.setVisible(false);
            this.jtxt_tipo.setVisible(false);
        }
    }//GEN-LAST:event_jrbtn_impresoraActionPerformed

    private void jrbtn_computadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jrbtn_computadorFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrbtn_computadorFocusLost

    private void jbtn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ingresarActionPerformed
        // TODO add your handling code here:
        
        String nombre;
        int id,precio;
        
        nombre = this.jtxt_nombre.getText();
        
        id = Integer.parseInt(this.jtxt_id.getText());
        precio = Integer.parseInt(this.jtxt_precio.getText());
        
        Coleccion col = new Coleccion();
        
        if (this.jrbtn_computador.isSelected()){
            Computador compu = new Computador();
            
            String ram,marca;
            ram = this.jtxt_ram.getText();
            marca = this.jtxt_marcaPc.getText();
            
//            Computador compu = new Computador(ram, marca, id, precio, nombre);
            
            compu.setCapacidadRAM(ram);
            compu.setId(id);
            compu.setMarca(marca);
            compu.setNombre(nombre);
            compu.setPrecio(precio);
            col.agregarProducto(compu);
            JOptionPane.showMessageDialog(rootPane,"Computador Agregado", "Agregar", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            
        }else{
            if (this.jrbtn_impresora.isSelected()){
                Impresora imp = new Impresora();
                
                String marca, tipo;
                
                marca = jtxt_marcaImp.getText();
                tipo = jtxt_tipo.getText();
                
//                Impresora imp = new Impresora(marca, tipo, id, precio, nombre);
                
                imp.setId(id);
                imp.setMarca(marca);
                imp.setNombre(nombre);
                imp.setPrecio(precio);
                imp.setTipo(tipo);
                col.agregarProducto(imp);
                JOptionPane.showMessageDialog(rootPane,"Impresora Agregada", "Agregar", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jbtn_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(From_Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(From_Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(From_Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(From_Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new From_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbrtn_volver;
    private javax.swing.JButton jbtn_ingresar;
    private javax.swing.JLabel jlbl_id;
    private javax.swing.JLabel jlbl_marcaimp;
    private javax.swing.JLabel jlbl_marcapc;
    private javax.swing.JLabel jlbl_nombre;
    private javax.swing.JLabel jlbl_precio;
    private javax.swing.JPanel jlbl_producot;
    private javax.swing.JLabel jlbl_ram;
    private javax.swing.JLabel jlbl_tipo;
    private javax.swing.JRadioButton jrbtn_computador;
    private javax.swing.JRadioButton jrbtn_impresora;
    private javax.swing.JTextField jtxt_id;
    private javax.swing.JTextField jtxt_marcaImp;
    private javax.swing.JTextField jtxt_marcaPc;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_precio;
    private javax.swing.JTextField jtxt_ram;
    private javax.swing.JTextField jtxt_tipo;
    // End of variables declaration//GEN-END:variables
}
